# Generated by Django 4.2.11 on 2024-04-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_studysession_historicalstudysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallanguage',
            name='icon',
            field=models.TextField(blank=True, max_length=100, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.FileField(blank=True, upload_to='', verbose_name='Icon'),
        ),
    ]
