# Generated by Django 4.2.11 on 2024-04-07 15:25

import ankit_api.users.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_sessions", "0003_alter_historicallanguage_icon_alter_language_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstudysession",
            name="cards_added",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Cards added"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudysession",
            name="duration_in_minutes",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                verbose_name="Duration in minutes",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudysession",
            name="spreadsheet_file",
            field=models.TextField(
                blank=True, max_length=100, verbose_name="Spreadsheet file"
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="cards_added",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Cards added"
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="duration_in_minutes",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                verbose_name="Duration in minutes",
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="spreadsheet_file",
            field=models.FileField(
                blank=True,
                upload_to=ankit_api.users.utils.user_directory_path,
                verbose_name="Spreadsheet file",
            ),
        ),
    ]
