# Generated by Django 4.2.11 on 2024-05-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0005_rename_spreadsheet_file_historicalstudysession_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallanguage',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_log', to='study_sessions.language'),
            preserve_default=False,
        ),
    ]
