# Generated by Django 4.2.11 on 2024-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0006_historicallanguage_history_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudysession',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_log', to='study_sessions.studysession'),
            preserve_default=False,
        ),
    ]
