# Generated by Django 4.2.11 on 2024-05-09 12:41

from django.db import migrations
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0007_historicalstudysession_history_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudysession',
            name='language',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_sessions.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='language',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='study_sessions.language', verbose_name='Language'),
        ),
    ]
