# Generated by Django 4.2.11 on 2024-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0008_alter_historicalstudysession_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudysession',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
