from django.core.management.base import BaseCommand

from ankit_api.users.models import Nationality


class Command(BaseCommand):
    help = "Creates nationalities"

    def handle(self, *args, **options) -> str | None:
        nationalities = (
            "Antiguano",
            "Argentino",
            "Bahamense",
            "Barbadiano, barbadense",
            "Belizenho",
            "Boliviano",
            "Brasileiro",
            "Chileno",
            "Colombiano",
            "Costarriquenho",
            "Cubano",
            "Dominicano",
            "Equatoriano",
            "Salvadorenho",
            "Granadino",
            "Guatemalteco",
            "Guianês",
            "Guianense",
            "Haitiano",
            "Hondurenho",
            "Jamaicano",
            "Mexicano",
            "Nicaraguense",
            "Panamenho",
            "Paraguaio",
            "Peruano",
            "Portorriquenho",
            "Dominicana",
            "São-cristovense",
            "São-vicentino",
            "Santa-lucense",
            "Surinamês",
            "Trindadense",
            "Uruguaio",
            "Venezuelano",
            "Alemão",
            "Austríaco",
            "Belga",
            "Croata",
            "Dinamarquês",
            "Eslovaco",
            "Esloveno",
            "Espanhol",
            "Francês",
            "Grego",
            "Húngaro",
            "Irlandês",
            "Italiano",
            "Noruego",
            "Holandês",
            "Polonês",
            "Português",
            "Britânico",
            "Inglês",
            "Galês",
            "Escocês",
            "Romeno",
            "Russo",
            "Sérvio",
            "Sueco",
            "Suíço",
            "Turco",
            "Ucraniano",
            "Americano",
            "Canadense",
            "Angolano",
            "Moçambicano",
            "Sul-africano",
            "Zimbabuense",
            "Argélia",
            "Comorense",
            "Egípcio",
            "Líbio",
            "Marroquino",
            "Ganés",
            "Queniano",
            "Ruandês",
            "Ugandense",
            "Bechuano",
            "Marfinense",
            "Camaronense",
            "Nigeriano",
            "Somali",
            "Australiano",
            "Neozelandês",
            "Afegão",
            "Saudita",
            "Armeno",
            "Bangladesh",
            "Chinês",
            "Norte-coreano, coreano",
            "Sul-coreano, coreano",
            "Indiano",
            "Indonésio",
            "Iraquiano",
            "Iraniano",
            "Israelita",
            "Japonês",
            "Malaio",
            "Nepalês",
            "Omanense",
            "Paquistanês",
            "Palestino",
            "Qatarense",
            "Sírio",
            "Cingalês",
            "Tailandês",
            "Timorense, maubere",
            "Árabe, emiratense",
            "Vietnamita",
            "Iemenita",
        )
        for nationality in nationalities:
            Nationality.objects.get_or_create(name=nationality)

        self.stdout.write(
            self.style.SUCCESS("Nationalities successfully inserted into database."),
        )
