# Generated by Django 4.2.11 on 2024-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='studied_today',
            field=models.BooleanField(default=False, verbose_name='Studied today'),
        ),
        migrations.AddField(
            model_name='user',
            name='studied_today',
            field=models.BooleanField(default=False, verbose_name='Studied today'),
        ),
    ]
