# Generated by Django 4.2.11 on 2024-04-24 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicaluser_studied_today_user_studied_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='educational_level',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='studied_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='educational_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='studied_today',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('educational_level', models.CharField(choices=[('Middle School', 'Ensino Fundamental'), ('High School', 'Ensino Médio'), ('University', 'Superior')], max_length=13, verbose_name='Educational level')),
                ('streak', models.PositiveSmallIntegerField(default=0, verbose_name='Streak')),
                ('longest_streak', models.PositiveSmallIntegerField(default=0, verbose_name='Longest streak')),
                ('studied_today', models.BooleanField(default=False, verbose_name='Studied today')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.nationality', verbose_name='Nationality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('educational_level', models.CharField(choices=[('Middle School', 'Ensino Fundamental'), ('High School', 'Ensino Médio'), ('University', 'Superior')], max_length=13, verbose_name='Educational level')),
                ('streak', models.PositiveSmallIntegerField(default=0, verbose_name='Streak')),
                ('longest_streak', models.PositiveSmallIntegerField(default=0, verbose_name='Longest streak')),
                ('studied_today', models.BooleanField(default=False, verbose_name='Studied today')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.nationality', verbose_name='Nationality')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical Student',
                'verbose_name_plural': 'historical Students',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
