# Generated by Django 4.2.11 on 2024-04-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_historicaluser_educational_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.nationality', verbose_name='Nationality'),
            preserve_default=False,
        ),
    ]
