# Generated by Django 4.2.11 on 2024-05-06 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='total_study_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total study time'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_study_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total study time'),
        ),
    ]
