# Generated by Django 4.2.11 on 2024-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_historicalstudent_total_study_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_log', to='users.student'),
            preserve_default=False,
        ),
    ]
