# Generated by Django 4.2.11 on 2024-05-09 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_historicalstudent_history_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnationality',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_log', to='users.nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_log', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='nationality',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='user',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='User'),
        ),
    ]
