# Generated by Django 4.2.11 on 2024-08-11 14:40

import ankit_api.utils.upload_to_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_historicalstudent_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=100, verbose_name='Profile picture'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=ankit_api.utils.upload_to_funcs.user_directory_path, verbose_name='Profile picture'),
        ),
    ]
