name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  # With no caching at all the entire ci process takes 3m to complete!
  # pytest:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v4

  #     - name: Build the Stack
  #       run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .django && docker compose -f local.yml build django

  #     - name: Run DB Migrations
  #       run: docker compose -f local.yml run --rm django python manage.py migrate

  #     - name: Run Django Tests
  #       run: docker compose -f local.yml run django pytest

  #     - name: Tear down the Stack
  #       run: docker compose -f local.yml down

  deploy:
    runs-on: ubuntu-latest
    needs: ["linter"]
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AMAZON_AWS_SSH_KEY }}" > ~/.ssh/ankit_api_amazon.pem
          chmod 600 ~/.ssh/ankit_api_amazon.pem
          ssh-keyscan ankit.backend.gentil.dev.br >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/ankit_api_amazon.pem ubuntu@ankit.backend.gentil.dev.br

      - name: Deploy Application
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_REPO_CLONE_KEY }}" > ~/.ssh/repo_clone_ssh_key
          chmod 600 ~/.ssh/repo_clone_ssh_key
          sudo rm -rf Ankit-Backend/
          GIT_SSH_COMMAND='ssh -i ~/.ssh/repo_clone_ssh_key' git clone git@github.com:gentil-eilison/Ankit-Backend.git
          git stash
          docker compose -f production.yml build && docker compose -f production.yml up
